-- Snowflake Schema Setup for SYNTRA Mastery System
-- Run this ENTIRE script in Snowflake UI as ACCOUNTADMIN

USE DATABASE SYNTRA_DB;
USE SCHEMA PUBLIC;

-- Create USER_INTERACTIONS table
CREATE TABLE IF NOT EXISTS USER_INTERACTIONS (
    USER_ID VARCHAR(255) NOT NULL,
    NODE_ID VARCHAR(255) NOT NULL,
    INTERACTION_TYPE VARCHAR(50) NOT NULL,
    DURATION_SECONDS INT DEFAULT 0,
    METADATA VARIANT,
    TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create MASTERY_SCORES table
CREATE TABLE IF NOT EXISTS MASTERY_SCORES (
    USER_ID VARCHAR(255) NOT NULL,
    NODE_ID VARCHAR(255) NOT NULL,
    MASTERY_SCORE FLOAT DEFAULT 0,
    REVISIT_COUNT INT DEFAULT 0,
    TOTAL_TIME_SPENT INT DEFAULT 0,
    SUBTOPICS_EXPLORED INT DEFAULT 0,
    CONTENT_READ_PCT FLOAT DEFAULT 0,
    LAST_VISITED TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID, NODE_ID)
);

-- Create RECOMMENDATIONS table
CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    USER_ID VARCHAR(255) NOT NULL,
    RECOMMENDED_NODE_ID VARCHAR(255) NOT NULL,
    CONFIDENCE_SCORE FLOAT DEFAULT 0,
    REASON VARCHAR(500),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- GRANT PERMISSIONS to PUBLIC role (which SYNTRA_APP uses)
GRANT USAGE ON DATABASE SYNTRA_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SYNTRA_DB.PUBLIC TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SYNTRA_DB.PUBLIC TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SYNTRA_DB.PUBLIC TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE SYNTRA TO ROLE PUBLIC;

-- Verify tables were created
SHOW TABLES;

-- Verify grants were applied
SHOW GRANTS TO ROLE PUBLIC;
