-- Snowflake Schema Setup for SYNTRA Mastery System
-- Run this in Snowflake SQL Editor

USE DATABASE SYNTRA_DB;
USE SCHEMA PUBLIC;

-- Create USER_INTERACTIONS table
CREATE TABLE IF NOT EXISTS USER_INTERACTIONS (
    USER_ID VARCHAR NOT NULL,
    NODE_ID VARCHAR NOT NULL,
    INTERACTION_TYPE VARCHAR NOT NULL,
    DURATION_SECONDS NUMBER,
    METADATA VARIANT,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID, NODE_ID, INTERACTION_TYPE, TIMESTAMP)
);

-- Create MASTERY_SCORES table
CREATE TABLE IF NOT EXISTS MASTERY_SCORES (
    USER_ID VARCHAR NOT NULL,
    NODE_ID VARCHAR NOT NULL,
    MASTERY_SCORE NUMBER(5,2),
    REVISIT_COUNT NUMBER DEFAULT 0,
    TOTAL_TIME_SPENT NUMBER DEFAULT 0,
    SUBTOPICS_EXPLORED NUMBER DEFAULT 0,
    CONTENT_READ_PCT NUMBER DEFAULT 0,
    LAST_VISITED TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID, NODE_ID)
);

-- Create RECOMMENDATIONS table (for future use)
CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    USER_ID VARCHAR NOT NULL,
    RECOMMENDED_NODE_ID VARCHAR NOT NULL,
    CONFIDENCE_SCORE NUMBER(5,2),
    REASON VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID, RECOMMENDED_NODE_ID)
);

-- Verify tables were created
SHOW TABLES;
